version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

  build-verify:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Assemble release build
          command: |
            ./gradlew clean assemble

  deploy-to-sonatype:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Define ORG_GRADLE_PROJECT_LIBRARY_VERSION Environment Variable at Runtime
          command: |
            if [ $CIRCLE_TAG ]
              then
                echo 'export ORG_GRADLE_PROJECT_LIBRARY_VERSION=$CIRCLE_TAG' >> $BASH_ENV
              else
                echo "export ORG_GRADLE_PROJECT_LIBRARY_VERSION=`git tag | tail -1`-SNAPSHOT" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Inject Maven signing key
          command: |
            echo $GPG_SIGNING_KEY \
              | awk 'NR == 1 { print "SIGNING_KEY=" } 1' ORS='\\n' \
              >> gradle.properties
      - run:
          name: Publish to Maven
          command: ./gradlew assemble publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - build-verify:
          name: build-test
          filters:
            tags:
              only: /^[0-9]+.*/ 
      - hold-for-approval:
          type: approval
          requires:
            - build-test
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
      - deploy-to-sonatype:
          name: Deploy to Maven Central
          requires:
            - hold-for-approval
          filters:
            tags:
              only: /^[0-9]+.*/
